<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Addon;

class AddonsFacilitySeeder extends Seeder
{
    public function run(): void
    {
        $adminUser = User::where('utype', 'ADM')->first();

        if (!$adminUser) {
            $adminUser = User::create([
                'name'     => 'Admin User',
                'email'    => 'admin@example.com',
                'password' => bcrypt('password'),
                'utype'    => 'ADM',
            ]);
        }

        $facilityId = 1;

        $addons = [
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'GOGGLES',
                'price_type'            => 'per_item',
                'description'           => 'ASDASAD',
                'base_price'            => 100.00,
                'capacity'              => null,
                'quantity'              => 0,
                'is_based_on_quantity'  => true,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_day',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'CATERING FEE',
                'price_type'            => 'flat_rate',
                'description'           => 'ADASDAS',
                'base_price'            => 5000.00,
                'capacity'              => null,
                'quantity'              => 0,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_day',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'WMF',
                'price_type'            => 'flat_rate',
                'description'           => 'ASDADASDASDSA',
                'base_price'            => 1000.00,
                'capacity'              => null,
                'quantity'              => 0,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => true,
                'billing_cycle'         => 'per_day',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'EXTRA PERSON',
                'price_type'            => 'per_night',
                'description'           => 'ADADASDADA',
                'base_price'            => 150.00,
                'capacity'              => null,
                'quantity'              => 0,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_day',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'PAVILLION 1',
                'price_type'            => 'per_unit',
                'description'           => 'ASDADSADSA',
                'base_price'            => 500.00,
                'capacity'              => 15,
                'quantity'              => 1,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_day',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Parking Space',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 100.00,
                'capacity'              => 50,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Hotel Kits',
                'price_type'            => 'per_item',
                'description'           => null,
                'base_price'            => 50.00,
                'capacity'              => null,
                'quantity'              => 99,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Cleaning Fee',
                'price_type'            => 'flat_rate',
                'description'           => null,
                'base_price'            => 500.00,
                'capacity'              => null,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Electric Fan',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 500.00,
                'capacity'              => 100,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],

            // NEW items (appended below, same format as Electric Fan)
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Radio / Cassette',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 325.00,
                'capacity'              => 100,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Computer / Laptop',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 500.00,
                'capacity'              => 100,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Television',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 400.00,
                'capacity'              => 100,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Cellular Phone',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 150.00,
                'capacity'              => 100,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Refrigerator',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 1500.00,
                'capacity'              => 50,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Flat Iron',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 825.00,
                'capacity'              => 100,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
            [
                'facility_id'           => $facilityId,
                'facility_attribute_id' => null,
                'user_id'               => $adminUser->id,
                'name'                  => 'Foam',
                'price_type'            => 'per_unit',
                'description'           => null,
                'base_price'            => 500.00,
                'capacity'              => 100,
                'quantity'              => null,
                'is_based_on_quantity'  => false,
                'is_available'          => true,
                'is_refundable'         => false,
                'billing_cycle'         => 'per_contract',
                'show'                  => 'both',
            ],
        ];

        foreach ($addons as $addon) {
            Addon::updateOrCreate(
                ['facility_id' => $addon['facility_id'], 'name' => $addon['name']],
                $addon
            );
        }
    }
}
