<?php

return [
    [
        'name'       => 'Umbrella',
        'category'   => 'Accessories > Umbrella',
        'price'      => 220,
        'attributes' => [],
    ],
    [
        'name'       => 'Keychain',
        'category'   => 'Accessories > Keychain',
        'price'      => 100,
        'attributes' => [],
    ],
    [
        'name'       => 'Keychain for Car',
        'category'   => 'Accessories > Keychain',
        'price'      => 100,
        'attributes' => [],
    ],
    [
        'name'       => 'CVSU Mug',
        'category'   => 'Home & Kitchen > Mug',
        'price'      => 70,
        'attributes' => [
            'CvSU Mug' => [
                'CvSU Mug'        => 70,
                'CvSU Mug w/ Box' => 80,
            ],
        ],
    ],
    [
        'name'       => 'Cap',
        'category'   => 'Apparel > Cap',
        'attributes' => [],
    ],
    [
        'name'       => 'Bonnet',
        'category'   => 'Apparel > Bonnet',
        'attributes' => [],
    ],
    [
        'name'       => 'T-Shirt',
        'category'   => 'Apparel > T-Shirt',
        'price'      => 220,
        'attributes' => [],
    ],
    [
        'name'       => 'Polo Shirt',
        'category'   => 'Apparel > Polo',
        'price'      => 240,
        'attributes' => [],
    ],
    [
        'name'       => 'Case of Utensils',
        'category'   => 'Home & Kitchen > Utensils',
        'attributes' => [],
    ],
    [
        'name'       => 'Notebook',
        'category'   => 'Stationery > Notebook',
        'price'      => 125,
        'attributes' => [],
    ],
    [
        'name'       => 'Coffee Blend',
        'category'   => 'Home & Kitchen > Coffee Blend',
        'price'      => 250,
        'attributes' => [
            'Types' => [
                'Naturally-Sweetened'  => 280,
                'Liberica-Based'       => 260,
                'Antioxidant-Enriched'  => 290,
                'Original Blend'       => 250,
            ],
        ],
    ],
    [
        'name'       => 'Fans',
        'category'   => 'Home & Kitchen > Fans',
        'price'      => 50,
        'attributes' => [],
    ],
    [
        'name'       => 'Lace',
        'category'   => 'Accessories > Lace',
        'price'      => 70,
        'attributes' => [],
    ],
    [
        'name'       => 'Jacket',
        'category'   => 'Apparel > Jacket',
        'price'      => 660,
        'attributes' => [],
    ],
    [
        'name'       => 'Ballpens',
        'category'   => 'Stationery > Ballpens',
        'price'      => 40,
        'attributes' => [],
    ],
    [
        'name'       => 'Books',
        'category'   => 'Stationery > Books',
        'attributes' => [],
    ],
    // New products with variant prices:
    [
        'name'       => 'Blouse',
        'category'   => 'Apparel > Female Uniform',
        'price'      => 275,
        'attributes' => [
            'Sizes' => [
                'xs'  => 275,
                's'   => 275,
                'm'   => 275,
                'l'   => 275,
                'xl'  => 290,
                '2xl' => 300,
                '3xl' => 315,
                '4xl' => 330,
                '5xl' => 340,
                '6xl' => 350,
            ],
        ],
    ],
    [
        'name'       => 'Slacks',
        'category'   => 'Apparel > Female Uniform',
        'price'      => 320,
        'attributes' => [
            'Sizes' => [
                'xs'  => 320,
                's'   => 340,
                'm'   => 360,
                'l'   => 375,
                'xl'  => 400,
                '2xl' => 415,
                '3xl' => 435,
                '4xl' => 450,
                '5xl' => 470,
                '6xl' => 490,
            ],
        ],
    ],
    [
        'name'       => 'pe tshirt',
        'category'   => 'Apparel > PE',
        'price'      => 270,
        'attributes' => [
            'Sizes' => [
                'xs'  => 250,
                's'   => 250,
                'm'   => 250,
                'l'   => 250,
                'xl'  => 270,
                '2xl' => 275,
                '3xl' => 290,
                '4xl' => 300,
                '5xl' => 315,
                '6xl' => 325,
            ],
        ],
    ],
    [
        'name'       => 'pe short',
        'category'   => 'Apparel > PE',
        'price'      => 270,
        'attributes' => [
            'Sizes' => [
                'xs'  => 250,
                's'   => 250,
                'm'   => 250,
                'l'   => 250,
                'xl'  => 270,
                '2xl' => 275,
                '3xl' => 290,
                '4xl' => 300,
                '5xl' => 315,
                '6xl' => 325,
            ],
        ],
    ],
    [
        'name'       => 'polo',
        'category'   => 'Apparel > Male Uniform',
        'price'      => 315,
        'attributes' => [
            'Sizes' => [
                'xs'  => 315,
                's'   => 315,
                'm'   => 315,
                'l'   => 315,
                'xl'  => 335,
                '2xl' => 350,
                '3xl' => 370,
                '4xl' => 390,
                '5xl' => 410,
                '6xl' => 425,
            ],
        ],
    ],
    [
        'name'       => 'NSTP t-shirt',
        'category'   => 'Apparel > NSTP',
        'price'      => 250,
        'attributes' => [
            'Sizes' => [
                'xs'  => 250,
                's'   => 250,
                'm'   => 250,
                'l'   => 250,
                'xl'  => 270,
                '2xl' => 275,
                '3xl' => 290,
                '4xl' => 300,
                '5xl' => 315,
                '6xl' => 325,
            ],
        ],
    ],
    [
        'name'       => 'cspear tshirt',
        'category'   => 'Apparel > Cspear',
        'price'      => 260,
        'attributes' => [
            'Sizes' => [
                'xs'  => 260,
                's'   => 260,
                'm'   => 260,
                'l'   => 260,
                'xl'  => 275,
                '2xl' => 285,
                '3xl' => 300,
                '4xl' => 310,
            ],
        ],
    ],
    [
        'name'       => 'cspear short',
        'category'   => 'Apparel > Cspear',
        'price'      => 310,
        'attributes' => [
            'Sizes' => [
                'xs'  => 310,
                's'   => 310,
                'm'   => 325,
                'l'   => 325,
                'xl'  => 335,
                '2xl' => 350,
                '3xl' => 360,
                '4xl' => 375,
            ],
        ],
    ],
    [
        'name'       => 'cspear jogging pants',
        'category'   => 'Apparel > Cspear',
        'price'      => 400,
        'attributes' => [
            'Sizes' => [
                'xs'  => 400,
                's'   => 410,
                'm'   => 425,
                'l'   => 435,
                'xl'  => 450,
                '2xl' => 460,
                '3xl' => 475,
                '4xl' => 485,
            ],
        ],
    ],
    [
        'name'       => 'semi-golf umbrella manual',
        'category'   => 'Accessories > Umbrella',
        'price'      => 280,
        'attributes' => [],
    ],
    [
        'name'       => 'semi-golf umbrella automatic',
        'category'   => 'Accessories > Umbrella',
        'price'      => 340,
        'attributes' => [],
    ],
    [
        'name'       => 'cvsu pin',
        'category'   => 'Accessories > Pin',
        'price'      => 100,
        'attributes' => [],
    ],
    [
        'name'       => 'tumbler',
        'category'   => 'Home & Kitchen > Tumbler',
        'price'      => 220,
        'attributes' => [],
    ],
];
